# Generated by Django 5.2.6 on 2025-09-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driverdocuments_driververification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driververification',
            name='admin_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
