# Generated by Django 5.2.6 on 2025-09-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_driververification_admin_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driververification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending'),
        ),
    ]
